# Generated by Django 5.2 on 2025-04-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
